package com.dewonderstruck.apps.ashx0.viewobject

import androidx.room.Embedded
import androidx.room.Entity
import com.google.gson.annotations.SerializedName

/**
 * Created by Vamsi Madduluri on 12/6/17.
 * Contact Email : vamsii.wrkhost@gmail.com
 */
@Entity(primaryKeys = ["userId"])
class User(@field:SerializedName("user_id") var userId: String, @field:SerializedName("user_is_sys_admin") var userIsSysAdmin: String, @field:SerializedName("is_shop_admin") var isShopAdmin: String, @field:SerializedName("facebook_id") var facebookId: String, @field:SerializedName("google_id") var googleId: String, @field:SerializedName("user_name") var userName: String, @field:SerializedName("user_email") var userEmail: String, @field:SerializedName("user_phone") var userPhone: String, @field:SerializedName("user_password") var userPassword: String, @field:SerializedName("user_about_me") var userAboutMe: String, @field:SerializedName("user_cover_photo") var userCoverPhoto: String, @field:SerializedName("user_profile_photo") var userProfilePhoto: String, @field:SerializedName("role_id") var roleId: String, @field:SerializedName("status") var status: String, @field:SerializedName("is_banned") var isBanned: String, @field:SerializedName("added_date") var addedDate: String, @field:SerializedName("billing_first_name") var billingFirstName: String, @field:SerializedName("billing_last_name") var billingLastName: String, @field:SerializedName("billing_company") var billingCompany: String, @field:SerializedName("billing_address_1") var billingAddress1: String, @field:SerializedName("billing_address_2") var billingAddress2: String, @field:SerializedName("billing_country") var billingCountry: String, @field:SerializedName("billing_state") var billingState: String, @field:SerializedName("billing_city") var billingCity: String, @field:SerializedName("billing_postal_code") var billingPostalCode: String, @field:SerializedName("billing_email") var billingEmail: String, @field:SerializedName("billing_phone") var billingPhone: String, @field:SerializedName("shipping_first_name") var shippingFirstName: String, @field:SerializedName("shipping_last_name") var shippingLastName: String, @field:SerializedName("shipping_company") var shippingCompany: String, @field:SerializedName("shipping_address_1") var shippingAddress1: String, @field:SerializedName("shipping_address_2") var shippingAddress2: String, @field:SerializedName("shipping_country") var shippingCountry: String, @field:SerializedName("shipping_state") var shippingState: String, @field:SerializedName("shipping_city") var shippingCity: String, @field:SerializedName("shipping_postal_code") var shippingPostalCode: String, @field:SerializedName("shipping_email") var shippingEmail: String, @field:SerializedName("shipping_phone") var shippingPhone: String, @field:SerializedName("device_token") var deviceToken: String, @field:SerializedName("code") var code: String, @field:SerializedName("verify_types") var verifyTypes: String, @field:SerializedName("added_date_str") var addedDateStr: String, @field:Embedded(prefix = "country") @field:SerializedName("country") var country: Country, @field:Embedded(prefix = "city") @field:SerializedName("city") var city: City)