import com.dewonderstruck.apps.AppExecutors.networkIO
import com.dewonderstruck.apps.ashx0.api.ApiService.rawPostContact
import com.dewonderstruck.apps.ashx0.api.ApiResponse.isSuccessful
import com.dewonderstruck.apps.ashx0.viewobject.common.Resource.Companion.success
import com.dewonderstruck.apps.ashx0.viewobject.common.Resource.Companion.error
import com.dewonderstruck.apps.ashx0.db.CountryDao.deleteCountry
import com.dewonderstruck.apps.ashx0.db.CountryDao.insertAll
import com.dewonderstruck.apps.ashx0.db.CountryDao.allCountry
import com.dewonderstruck.apps.ashx0.api.ApiService.getCountryListWithShopId
import com.dewonderstruck.apps.ashx0.repository.common.NetworkBoundResource.asLiveData
import com.dewonderstruck.apps.AppExecutors.diskIO
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.countryDao
import com.dewonderstruck.apps.ashx0.db.CountryDao.insert
import com.dewonderstruck.apps.ashx0.api.ApiService.checkCouponDiscount
import com.dewonderstruck.apps.ashx0.db.ImageDao.deleteByImageIdAndType
import com.dewonderstruck.apps.ashx0.db.ImageDao.insertAll
import com.dewonderstruck.apps.ashx0.db.ImageDao.getByImageIdAndType
import com.dewonderstruck.apps.ashx0.api.ApiService.getImageList
import com.dewonderstruck.apps.ashx0.db.NotificationDao.deleteAllNotificationList
import com.dewonderstruck.apps.ashx0.db.NotificationDao.insertAllNotificationList
import com.dewonderstruck.apps.ashx0.db.NotificationDao.allNotificationList
import com.dewonderstruck.apps.ashx0.api.ApiService.getNotificationList
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.notificationDao
import com.dewonderstruck.apps.ashx0.db.NotificationDao.deleteNotificationById
import com.dewonderstruck.apps.ashx0.db.NotificationDao.insert
import com.dewonderstruck.apps.ashx0.db.NotificationDao.getNotificationById
import com.dewonderstruck.apps.ashx0.api.ApiService.getNotificationDetail
import com.dewonderstruck.apps.ashx0.api.ApiService.isReadNoti
import com.dewonderstruck.apps.ashx0.api.ApiResponse.nextPage
import com.dewonderstruck.apps.ashx0.api.ApiService.getPaypalToken
import com.dewonderstruck.apps.ashx0.viewobject.common.Resource.Companion.successWithMsg
import com.dewonderstruck.apps.ashx0.viewobject.holder.ProductParameterHolder.keyForProductMap
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.productMapDao
import com.dewonderstruck.apps.ashx0.db.ProductMapDao.deleteByMapKey
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.productDao
import com.dewonderstruck.apps.ashx0.db.ProductDao.insertAll
import com.dewonderstruck.apps.ashx0.db.ProductMapDao.insert
import com.dewonderstruck.apps.ashx0.db.ProductDao.getProductsByKey
import com.dewonderstruck.apps.ashx0.db.ProductDao.getProductsByKeyByLimit
import com.dewonderstruck.apps.ashx0.api.ApiService.searchProduct
import com.dewonderstruck.apps.ashx0.db.ProductMapDao.getMaxSortingByValue
import com.dewonderstruck.apps.ashx0.db.ProductDao.deleteAllRelatedProducts
import com.dewonderstruck.apps.ashx0.db.ProductDao.deleteAllBasedOnRelated
import com.dewonderstruck.apps.ashx0.db.ProductDao.insert
import com.dewonderstruck.apps.ashx0.db.ProductDao.allRelatedProducts
import com.dewonderstruck.apps.ashx0.api.ApiService.getProductDetailRelatedList
import com.dewonderstruck.apps.ashx0.db.ProductDao.deleteAllFavouriteProducts
import com.dewonderstruck.apps.ashx0.db.ProductDao.insertFavourite
import com.dewonderstruck.apps.ashx0.db.ProductDao.allFavouriteProducts
import com.dewonderstruck.apps.ashx0.api.ApiService.getFavouriteList
import com.dewonderstruck.apps.ashx0.db.ProductDao.maxSortingFavourite
import com.dewonderstruck.apps.ashx0.db.ProductDao.deleteAllProductListByCatIdVOs
import com.dewonderstruck.apps.ashx0.db.ProductDao.getAllProductListByCatId
import com.dewonderstruck.apps.ashx0.api.ApiService.getProductListByCatId
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.productColorDao
import com.dewonderstruck.apps.ashx0.db.ProductColorDao.deleteProductColorById
import com.dewonderstruck.apps.ashx0.db.ProductColorDao.insertAll
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.productSpecsDao
import com.dewonderstruck.apps.ashx0.db.ProductSpecsDao.deleteProductSpecsById
import com.dewonderstruck.apps.ashx0.db.ProductSpecsDao.insertAll
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.productAttributeHeaderDao
import com.dewonderstruck.apps.ashx0.db.ProductAttributeHeaderDao.deleteProductAttributeHeaderById
import com.dewonderstruck.apps.ashx0.db.ProductAttributeHeaderDao.insertAll
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.productAttributeDetailDao
import com.dewonderstruck.apps.ashx0.db.ProductAttributeDetailDao.deleteProductAttributeDetailById
import com.dewonderstruck.apps.ashx0.db.ProductAttributeDetailDao.insertAll
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.historyDao
import com.dewonderstruck.apps.ashx0.db.HistoryDao.insert
import com.dewonderstruck.apps.ashx0.db.ProductDao.getProductById
import com.dewonderstruck.apps.ashx0.api.ApiService.getProductDetail
import com.dewonderstruck.apps.ashx0.db.ProductDao.selectFavouriteById
import com.dewonderstruck.apps.ashx0.db.ProductDao.updateProductForFavById
import com.dewonderstruck.apps.ashx0.api.ApiService.setPostFavourite
import com.dewonderstruck.apps.ashx0.db.ProductDao.deleteFavouriteProductByProductId
import com.dewonderstruck.apps.ashx0.api.ApiService.setrawPostTouchCount
import com.dewonderstruck.apps.ashx0.db.ProductColorDao.getProductColorById
import com.dewonderstruck.apps.ashx0.db.ProductSpecsDao.getProductSpecsById
import com.dewonderstruck.apps.ashx0.db.ProductAttributeHeaderDao.getProductAttributeHeaderAndDetailById
import com.dewonderstruck.apps.AppExecutors.mainThread
import com.dewonderstruck.apps.ashx0.db.ProductAttributeDetailDao.getProductAttributeDetailById
import com.dewonderstruck.apps.ashx0.db.HistoryDao.getAllHistoryProductListData
import com.dewonderstruck.apps.ashx0.db.RatingDao.deleteAll
import com.dewonderstruck.apps.ashx0.db.RatingDao.insertAll
import com.dewonderstruck.apps.ashx0.db.RatingDao.getRatingById
import com.dewonderstruck.apps.ashx0.api.ApiService.getAllRatingList
import com.dewonderstruck.apps.ashx0.api.ApiService.postRating
import com.dewonderstruck.apps.ashx0.db.RatingDao.insert
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.shippingMethodDao
import com.dewonderstruck.apps.ashx0.db.ShippingMethodDao.deleteAll
import com.dewonderstruck.apps.ashx0.db.ShippingMethodDao.insertAll
import com.dewonderstruck.apps.ashx0.db.ShippingMethodDao.shippingMethods
import com.dewonderstruck.apps.ashx0.api.ApiService.getShipping
import com.dewonderstruck.apps.ashx0.api.ApiService.postShippingByCountryAndCity
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.shopDao
import com.dewonderstruck.apps.ashx0.db.ShopDao.insert
import com.dewonderstruck.apps.ashx0.db.ShopDao.shopById
import com.dewonderstruck.apps.ashx0.api.ApiService.getShopById
import com.dewonderstruck.apps.ashx0.db.SubCategoryDao.deleteAllSubCategory
import com.dewonderstruck.apps.ashx0.db.SubCategoryDao.insertAll
import com.dewonderstruck.apps.ashx0.db.SubCategoryDao.insert
import com.dewonderstruck.apps.ashx0.db.SubCategoryDao.allSubCategory
import com.dewonderstruck.apps.ashx0.api.ApiService.getAllSubCategoryList
import com.dewonderstruck.apps.ashx0.db.SubCategoryDao.getSubCategoryList
import com.dewonderstruck.apps.ashx0.api.ApiService.getSubCategoryListWithCatId
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.subCategoryDao
import com.dewonderstruck.apps.ashx0.db.TransactionDao.deleteAllTransactionList
import com.dewonderstruck.apps.ashx0.db.TransactionDao.insertAllTransactionList
import com.dewonderstruck.apps.ashx0.db.TransactionDao.allTransactionList
import com.dewonderstruck.apps.ashx0.db.TransactionDao.getAllTransactionListByLimit
import com.dewonderstruck.apps.ashx0.api.ApiService.getTransList
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.transactionDao
import com.dewonderstruck.apps.ashx0.api.ApiService.uploadTransactionHeader
import com.dewonderstruck.apps.ashx0.db.TransactionDao.deleteTransactionById
import com.dewonderstruck.apps.ashx0.db.TransactionDao.insert
import com.dewonderstruck.apps.ashx0.db.TransactionDao.getTransactionById
import com.dewonderstruck.apps.ashx0.api.ApiService.getTransactionDetail
import com.dewonderstruck.apps.ashx0.db.TransactionOrderDao.deleteAllTransactionOrderList
import com.dewonderstruck.apps.ashx0.db.TransactionOrderDao.insertAllTransactionOrderList
import com.dewonderstruck.apps.ashx0.db.TransactionOrderDao.getAllTransactionOrderList
import com.dewonderstruck.apps.ashx0.api.ApiService.getTransactionOrderList
import com.dewonderstruck.apps.ashx0.db.PSCoreDb.transactionOrderDao
import com.dewonderstruck.apps.ashx0.db.UserDao.deleteUserLogin
import com.dewonderstruck.apps.ashx0.db.UserDao.insert
import com.dewonderstruck.apps.ashx0.db.UserDao.getUserLoginData
import com.dewonderstruck.apps.ashx0.api.ApiService.postUserLogin
import com.dewonderstruck.apps.ashx0.db.UserDao.userLoginData
import com.dewonderstruck.apps.ashx0.db.UserDao.getUserData
import com.dewonderstruck.apps.ashx0.api.ApiService.getUser
import com.dewonderstruck.apps.ashx0.api.ApiService.postUser
import com.dewonderstruck.apps.ashx0.api.ApiService.postFBUser
import com.dewonderstruck.apps.ashx0.db.UserDao.update
import com.dewonderstruck.apps.ashx0.api.ApiService.putUser
import com.dewonderstruck.apps.ashx0.api.ApiService.postForgotPassword
import com.dewonderstruck.apps.ashx0.api.ApiService.postPasswordUpdate
import com.dewonderstruck.apps.ashx0.api.ApiService.doUploadImage
import com.dewonderstruck.apps.ashx0.api.ApiService.postGoogleLogin
import com.dewonderstruck.apps.ashx0.api.ApiService.verifyEmail
import com.dewonderstruck.apps.ashx0.api.ApiService.resentCodeAgain
import com.dewonderstruck.apps.ashx0.api.ApiService.postPhoneLogin
import javax.inject.Inject
import com.dewonderstruck.apps.ashx0.api.ApiService
import com.dewonderstruck.apps.AppExecutors
import com.dewonderstruck.apps.ashx0.db.PSCoreDb
import com.dewonderstruck.apps.ashx0.repository.common.PSRepository
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import com.dewonderstruck.apps.ashx0.viewobject.ApiStatus
import com.dewonderstruck.apps.ashx0.api.ApiResponse
import com.dewonderstruck.apps.ashx0.db.CountryDao
import com.dewonderstruck.apps.ashx0.viewobject.Country
import com.dewonderstruck.apps.ashx0.repository.common.NetworkBoundResource
import androidx.lifecycle.MediatorLiveData
import com.dewonderstruck.apps.ashx0.viewobject.CouponDiscount
import com.dewonderstruck.apps.ashx0.db.ImageDao
import com.dewonderstruck.apps.ashx0.db.NotificationDao
import com.dewonderstruck.apps.ashx0.viewobject.Noti
import com.dewonderstruck.apps.ashx0.db.ProductDao
import android.content.SharedPreferences
import com.dewonderstruck.apps.ashx0.viewobject.holder.ProductParameterHolder
import com.dewonderstruck.apps.ashx0.viewobject.ProductMap
import com.dewonderstruck.apps.ashx0.viewobject.RelatedProduct
import com.dewonderstruck.apps.ashx0.viewobject.FavouriteProduct
import com.dewonderstruck.apps.ashx0.viewobject.ProductListByCatId
import com.dewonderstruck.apps.ashx0.viewobject.HistoryProduct
import com.dewonderstruck.apps.ashx0.viewobject.ProductColor
import com.dewonderstruck.apps.ashx0.viewobject.ProductSpecs
import com.dewonderstruck.apps.ashx0.viewobject.ProductAttributeHeader
import com.dewonderstruck.apps.ashx0.viewobject.ProductAttributeDetail
import com.dewonderstruck.apps.ashx0.db.RatingDao
import com.dewonderstruck.apps.ashx0.db.ShippingMethodDao
import com.dewonderstruck.apps.ashx0.viewobject.ShippingCostContainer
import com.dewonderstruck.apps.ashx0.viewobject.ShippingCost
import com.dewonderstruck.apps.ashx0.db.ShopDao
import com.dewonderstruck.apps.ashx0.viewobject.Shop
import com.dewonderstruck.apps.ashx0.db.SubCategoryDao
import com.dewonderstruck.apps.ashx0.viewobject.SubCategory
import com.dewonderstruck.apps.ashx0.db.TransactionDao
import com.dewonderstruck.apps.ashx0.viewobject.TransactionObject
import com.dewonderstruck.apps.ashx0.viewobject.TransactionHeaderUpload
import com.dewonderstruck.apps.ashx0.db.TransactionOrderDao
import com.dewonderstruck.apps.ashx0.viewobject.TransactionDetail
import com.dewonderstruck.apps.ashx0.db.UserDao
import com.dewonderstruck.apps.ashx0.viewobject.UserLogin
import com.dewonderstruck.apps.ashx0.utils.AbsentLiveData
import okhttp3.RequestBody
import okhttp3.MultipartBody